export const articlesActionTypes = {
  SET_ARTICLES: 'SET_ARTICLES',
  SET_ARTICLE: 'SET_ARTICLE',
  REMOVE_ARTICLE: 'REMOVE_ARTICLE',
  SET_SINGLE_ARTICLE: 'SET_SINGLE_ARTICLE',
  REMOVE_SINGLE_ARTICLE: 'REMOVE_SINGLE_ARTICLE',
  EDIT_ARTICLE: 'EDIT_ARTICLE'
}
